spring.application.name=Enterprise_Apps_Rayane_Laroub
# H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop

# H2 console (handig om je database te bekijken)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Toon SQL queries in de console
spring.jpa.show-sql=true